// db common key
String doc_field_first = 'First';
String doc_field_last = 'Last';
String doc_field_email = 'Email';
String doc_field_passwd = 'Passwd';
String doc_field_userid = 'Userid';
String session_key = 'session';
String session_userid = 'userid';
String string_true = 'true';
String string_false = 'false';
String e_code_user_not_found = 'user-not-found';
